src/quizzle-web/src/main/java/com/omnicorp/jsf/SelectQuizBean.java
package com.omnicorp.jsf;

import java.io.IOException;
import java.io.Serializable;
import java.util.Base64;
import java.util.List;

import javax.inject.Named;
import javax.servlet.http.HttpSession;
import javax.ws.rs.client.*;
import javax.ws.rs.core.MediaType;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.ejb.Startup;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.type.TypeFactory;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.*;
import javax.faces.context.FacesContext;

import com.omnicorp.model.Quiz;

import com.omnicorp.jsonToModelConv.QuizConverter;


@Named("selectQuizBean")
@SessionScoped
public class SelectQuizBean implements Serializable {
    private String userName = "Guest";
    private List<Quiz> quizzes;
    private Quiz currentSelection;
    private String difficulty;
    private float sizePercent;
    private int size;


    @PostConstruct
    public void init() {
        quizzes = QuizConverter.getQuizzes();

        if(quizzes.size()>0) {
            currentSelection = quizzes.get(0);
        }
        sizePercent = 100.0f;
        size = 100;
        difficulty = "1";
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public List<Quiz> getQuizzes() {
        return quizzes;
    }

    public void setQuizzes(List<Quiz> quizzes) {
        this.quizzes = quizzes;
    }

    public Quiz getCurrentSelection() {
        return currentSelection;
    }

    public void setCurrentSelection(Quiz currentSelection) {
        this.currentSelection = currentSelection;
    }

    public String getDifficulty() {
        return difficulty;
    }

    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty;
    }

    public float getSizePercent() {
        return sizePercent;
    }

    public void setSizePercent(float sizePercent) {
        this.sizePercent = sizePercent;
    }

    public int getSize() {
        return size;
    }

    public void setSize(int size) {
        this.size = size;
    }

    public void validateQuizSelection(FacesContext context, UIComponent comp, Object value) {
        if (value == null) {
            ((UIInput) comp).setValid(false);
            FacesMessage message = new FacesMessage("No Quiz Selected");
            context.addMessage(comp.getClientId(context), message);
        }
    }

    public void select() throws IOException {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(true);
        session.setAttribute("selectQuiz.selectedQuizId", currentSelection.getId());
        facesContext.getExternalContext().redirect("takeQuiz.xhtml");
    }

}

src/quizzle-web/src/main/java/com/omnicorp/jsf/TakeQuizBean.java
package com.omnicorp.jsf;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;

import com.omnicorp.model.*;

import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import com.omnicorp.jsonToModelConv.QuizConverter;
import com.omnicorp.dao.QuizDao;
import com.omnicorp.business.Ranking;


@Named("takeQuizBean")
// TODO: later, when transition to/from comments is implemented, make this ConversationScoped
//@javax.enterprise.context.SessionScoped
@ViewScoped
public class TakeQuizBean implements Serializable {
    private static Logger LOGGER = Logger.getLogger(TakeQuizBean.class.getName());
    @EJB Ranking ranking;

    static private class State {
        private static List<Question> questions;
        private static List<List<MultipleChoiceItem>> selectedAsCorrect; // the user selected these as being correct
        private static int currentQuestionIndex;
        private static Long selectedQuizId;

        static {init();}

        private static void init() {
            questions = null;
            selectedAsCorrect=null;
            currentQuestionIndex=-1;
            selectedQuizId = -1L;
        }

        static void store() {
            getSession().setAttribute("takeQuiz.questions",questions);
            getSession().setAttribute("takeQuiz.currentQuestionIndex",currentQuestionIndex);
            getSession().setAttribute("takeQuiz.selectedAsCorrect",selectedAsCorrect);
        }

        static void retrieve() {
                List<Question> questionsFromSession = (List<Question>)getSession().getAttribute("takeQuiz.questions");
            if(questionsFromSession!=null) {questions=questionsFromSession;}

            Integer indexFromSession = (Integer)getSession().getAttribute("takeQuiz.currentQuestionIndex");
            if(indexFromSession!=null) {currentQuestionIndex=indexFromSession;}
    
            var selectedAsCorrectFromSession = (List<List<MultipleChoiceItem>>)getSession().getAttribute("takeQuiz.selectedAsCorrect");
            if(selectedAsCorrectFromSession!=null) {selectedAsCorrect=selectedAsCorrectFromSession;}
    
            selectedQuizId = (Long)getSession().getAttribute("selectQuiz.selectedQuizId");
        }

        static void destroy() {
            getSession().removeAttribute("takeQuiz.questions");
            getSession().removeAttribute("takeQuiz.currentQuestionIndex");
            getSession().removeAttribute("takeQuiz.selectedAsCorrect");
            init();
        }

        private static HttpSession getSession() {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            return (HttpSession) facesContext.getExternalContext().getSession(false);
        }
    }


    @PostConstruct
    public void init() {
        LOGGER.log(Level.FINE, "TakeQuizBean.init");
        State.retrieve();
        if (State.currentQuestionIndex == -1) {
            State.questions = QuizConverter.getQuizById(State.selectedQuizId).getQuestions();
            if (State.questions != null && State.questions.size() > 0) {
                State.selectedAsCorrect = new ArrayList<>(State.questions.size());
                for(int i=0;i<State.questions.size();i++) {State.selectedAsCorrect.add(i,new ArrayList<MultipleChoiceItem>());}
                State.currentQuestionIndex = 0;
            } else {
                LOGGER.log(Level.WARNING, "No questions in this quiz");
            }
        } else {
            LOGGER.log(Level.FINE, "Data for quiz-taking retrieved from session");
        }
    }

    public String next() {
        if (State.questions.get(State.currentQuestionIndex) == null) {
            LOGGER.log(Level.WARNING, "No current question");
        } else {
            if(State.currentQuestionIndex<State.questions.size()-1) {
                State.currentQuestionIndex++;
                State.store();
            }
        }
        return "takeQuiz?faces-redirect=true";
    }

    public String previous()  {
        if (State.questions.get(State.currentQuestionIndex) == null) {
            LOGGER.log(Level.WARNING, "No current question");
        } else {
            if(State.currentQuestionIndex>0) {
                State.currentQuestionIndex--;
                State.store();
            }
        }
        return "takeQuiz?faces-redirect=true";
    }

    public String finito() {
        // TODO: check and warn if not all are answered
        for(int i=0;i<State.questions.size();i++) {
            State.selectedAsCorrect.get(i).stream().forEach(e->LOGGER.log(Level.FINE, e.getText()));
        }
        //List<Question> questions;     //TODO get questions of quiz from quizdao
        
        //validate(questions, State.questions);

        State.destroy();
        return "index";
    }

    public String giveUp() {
        State.destroy();
        return "index";
    }

    public String getCurrentQuestionText() {
        if (State.currentQuestionIndex > -1) {
            return State.questions.get(State.currentQuestionIndex).getText();
        }
        return "";
    }

    public List<MultipleChoiceItem> getAnswers() {
        return State.questions.get(State.currentQuestionIndex).getMultipleChoiceAnswer().getChoices();
    }

    public List<MultipleChoiceItem> getSelectedAsCorrect() {
        return State.selectedAsCorrect.get(State.currentQuestionIndex);
    }

    public void setSelectedAsCorrect(List<MultipleChoiceItem> selectedAsCorrect) {
        State.selectedAsCorrect.set(State.currentQuestionIndex, selectedAsCorrect);
    }

}


/*
datamodel:
    MultipleChoiceAnswer
        MultipleChoiceItem
            text
            isCorrect  
https://stackoverflow.com/questions/3694450/how-can-i-show-hide-component-with-jsf
*/

src/quizzle-web/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html
      PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html;charset=UTF-8" encoding="UTF-8">
      <h:head>

      </h:head>
      <h:body>
            <ui:composition template="/templates/template.xhtml">
                  <ui:define name="content">
                        <h:form>

                              <h:outputText
                                    value="Welcome to Quizzl, where you can take quizzes and also create your own." />
                              <br />
                              <p:commandButton action="selectQuiz" value="Take a quiz right away without login"
                                    icon="pi pi-play" iconPos="right" />
                              <br />
                              <p:commandButton value="Sign-in" icon="pi pi-sign-in" iconPos="right" />
                              <br />
                              <p:commandLink id="signup" style="margin-right:20px;">
                                    <h:outputText value="Sign-up" />
                              </p:commandLink>
                        </h:form>

                  </ui:define>
            </ui:composition>
      </h:body>
</f:view>

</html>

src/quizzle-web/src/main/webapp/selectQuiz.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html
      PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:jsf="http://xmlns.jcp.org/jsf"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html;charset=UTF-8" encoding="UTF-8">
      <h:head>

      </h:head>
      <h:body>
            <ui:composition template="/templates/template.xhtml">
                  <ui:define name="content">
                        <h:form>
                              <span class="ui-float-label">
                                    <p:inputText id="namebox" value="#{selectQuizBean.userName}" required="true"
                                          requiredMessage="Name is missing" style="padding: 20px" />
                                    <p:outputLabel for="@previous" value="Username" />
                              </span>
                              <p:outputLabel for="quizSelection" value="Please select the quiz you want to take" />
                              <br />
                              <p:selectOneListbox id="quizSelection" value="#{selectQuizBean.currentSelection}" var="e"
                                    filter="true" filterMatchMode="contains" required="true"
                                    requiredMessage="No quiz selected" validator="#{selectQuizBean.validateQuizSelection}">
                                    <f:converter converterId="quizConverter" />
                                    <f:selectItems value="#{selectQuizBean.quizzes}" var="blabla" itemValue="#{blabla}"
                                          itemLabel="#{blabla.name}" />
                                    <p:column>
                                          <h:outputText value="#{e.name}" />
                                    </p:column>
                                    <p:column>
                                          <h:outputText value="#{e.description}" />
                                    </p:column>
                              </p:selectOneListbox>

                              <h5 class="p-mt-0">Difficulty</h5>
                              <p:selectOneRadio id="difficulty" value="#{selectQuizBean.difficulty}" unselectable="true">
                                  <f:selectItem itemLabel="Easy" itemValue="0"/>
                                  <f:selectItem itemLabel="Intermediate" itemValue="1"/>
                                  <f:selectItem itemLabel="Hard" itemValue="2"/>
                              </p:selectOneRadio>

                              <h:panelGrid columns="1" style="margin-bottom: 10px">
                                    <h:outputText id="output" value="Size %#{selectQuizBean.sizePercent}" />
                                    <h:inputHidden id="txt2" value="#{selectQuizBean.size}" />
                                    <p:slider for="txt2" display="output" style="width: 200px"
                                          displayTemplate="Size %{value}" />
                              </h:panelGrid>

                              <p:message for="namebox" />
                              <br />
                              <p:message for="quizSelection" />
                              <p:messages>
                                    <p:autoUpdate />
                              </p:messages>
                              <p:commandButton action="#{selectQuizBean.select}" value="GO" icon="pi pi-play" iconPos="right" />
                              </h:form>
                  </ui:define>
            </ui:composition>
      </h:body>
</f:view>

</html>

src/quizzle-web/src/main/webapp/takeQuiz.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:jsf="http://xmlns.jcp.org/jsf"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets" xmlns:p="http://primefaces.org/ui">

<f:view contentType="text/html;charset=UTF-8" encoding="UTF-8">
    <h:head>

    </h:head>
    <h:body>
        <ui:composition template="/templates/template.xhtml">
            <ui:define name="content">
                <h:form>
                    <p:commandButton value="PREVIOUS" action="#{takeQuizBean.previous()}" icon="pi pi-step-backward" iconPos="left" >
                    </p:commandButton>
                    TODO: progress-pearls
                    <p:commandButton value="NEXT" action="#{takeQuizBean.next()}" icon="pi pi-step-forward" iconPos="right" >
                    </p:commandButton>

                    <br />
                    <h:outputText value="#{takeQuizBean.currentQuestionText}" id="currentQuestionText" />

                    <br />

                    <p:selectManyMenu id="multiplechoice" value="#{takeQuizBean.selectedAsCorrect}" var="e" showCheckbox="true" converterId="mciFacesConverter">
                        <p:column>
                            <h:outputText value="#{e.text}" />
                        </p:column>
                        <f:selectItems value="#{takeQuizBean.getAnswers()}" />
                    </p:selectManyMenu>

                    <br />
                    <p:commandButton value="Give up" onclick="PF('rusureDialog').show();" icon="pi pi-undo" iconPos="left" />
                    <p:commandButton value="Finito" action="#{takeQuizBean.finito()}" icon="pi pi-check" iconPos="right" />
                    <p:commandButton value="Comment" icon="pi pi-comment" iconPos="right" />
                </h:form>

                <p:dialog widgetVar="rusureDialog" closeable="true">
                    <h:outputText value="Are you sure to give up?" />
                    <br />
                    <h:outputText value="All progress will be lost." />
                    <br />
                    <p:commandButton value="Give up" action="giveUp()" />
                </p:dialog>

            </ui:define>
        </ui:composition>
    </h:body>
</f:view>

</html>